	;; Protect the suspended callback state in a synthetic frame before a nested invocation.
	;; Existing call, operand and control quotas apply across the complete nested chain.
	(func (export "begin_reentry") (param $index i32) (result i32)
		(local $frame i32)
		(local $stack i32)
		;; Only a suspended import has a host callback that can own the nested invocation.
		(if (i32.lt_s (global.get $pending-import) (i32.const 0))
			(then (return (i32.const M4_ERR_INVALID_RESUME)))
		)
		;; Invalid target indices cannot expose a descriptor or reserve any boundary state.
		(if (i32.ge_u (local.get $index) (global.get $function-count))
			(then (return (i32.const M4_ERR_INVALID_REFERENCE)))
		)
		;; Imported roots need only a boundary; defined roots also reserve their first guest frame.
		(if (i32.gt_u
			(i32.add (i32.add (global.get $gc-calls) (i32.const 1))
				(i32.ne (i32.load offset=M4_FUNCTION_START_OFFSET (call $function (local.get $index))) (i32.const M4_FUNCTION_IMPORTED)))
			(global.get $call-limit))
			(then (return (i32.const M4_ERR_RESOURCE_LIMIT)))
		)
		(local.set $stack (i32.add (global.get $sp)
			(i32.load offset=M4_FUNCTION_PARAMETERS_OFFSET
				(call $function (i32.load (call $import-record (global.get $pending-import)))))))
		;; Keep the outer callback arguments intact and precisely traceable while nested code executes.
		(if (i32.gt_u (local.get $stack) (global.get $operand-limit))
			(then (return (i32.const M4_ERR_RESOURCE_LIMIT)))
		)
		(local.set $frame (i32.add (global.get $call-base)
			(i32.mul (global.get $gc-calls) (global.get $call-bytes))))
		(i32.store offset=M4_REENTRY_ERROR_OFFSET (local.get $frame) (global.get $error))
		(i32.store offset=M4_REENTRY_OFFSET_OFFSET (local.get $frame) (global.get $offset))
		(i32.store offset=M4_REENTRY_TOK_OFFSET (local.get $frame) (global.get $tok))
		(i32.store offset=M4_REENTRY_LAST_RESULTS_OFFSET (local.get $frame) (global.get $last-results))
		(i32.store offset=M4_REENTRY_SP_OFFSET (local.get $frame) (global.get $sp))
		(i32.store offset=M4_REENTRY_CONTROL_COUNT_OFFSET (local.get $frame) (global.get $control-count))
		(i32.store offset=M4_REENTRY_SAVED_CALLS_OFFSET (local.get $frame) (global.get $saved-calls))
		(i32.store offset=M4_REENTRY_SAVED_FRAME_OFFSET (local.get $frame) (global.get $saved-frame))
		(i64.store offset=M4_REENTRY_SAVED_FUEL_OFFSET (local.get $frame) (global.get $saved-fuel))
		(i32.store offset=M4_REENTRY_RESUMING_OFFSET (local.get $frame) (global.get $resuming))
		(i32.store offset=M4_REENTRY_PENDING_IMPORT_OFFSET (local.get $frame) (global.get $pending-import))
		(i32.store offset=M4_REENTRY_PENDING_OFFSET_OFFSET (local.get $frame) (global.get $pending-offset))
		(i32.store offset=M4_REENTRY_GC_CALLS_OFFSET (local.get $frame) (global.get $gc-calls))
		(i32.store offset=M4_REENTRY_GC_PC_OFFSET (local.get $frame) (global.get $gc-pc))
		(i32.store offset=M4_REENTRY_GC_STACK_END_OFFSET (local.get $frame) (global.get $gc-stack-end))
		(i32.store offset=M4_REENTRY_EXCEPTION_PENDING_OFFSET (local.get $frame) (global.get $exception-pending))
		(i64.store offset=M4_REENTRY_EXCEPTION_VALUE_OFFSET (local.get $frame) (global.get $exception-value))
		(i32.store offset=M4_REENTRY_START_STATE_OFFSET (local.get $frame) (global.get $start-state))
		(i32.store offset=M4_REENTRY_REENTRY_FLOOR_OFFSET (local.get $frame) (global.get $reentry-floor))
		(i32.store offset=M4_REENTRY_REENTRY_STACK_OFFSET (local.get $frame) (global.get $reentry-stack))
		(i32.store offset=M4_REENTRY_REENTRY_CONTROL_OFFSET (local.get $frame) (global.get $reentry-control))
		(i32.store offset=M4_REENTRY_REENTRY_CONTEXT_OFFSET (local.get $frame) (global.get $reentry-context))
		(i32.store offset=M4_CALL_FUNCTION_OFFSET (local.get $frame) (i32.const -1))
		(i32.store offset=M4_CALL_STACK_BASE_OFFSET (local.get $frame) (local.get $stack))
		(global.set $reentry-context (local.get $frame))
		(global.set $reentry-floor (i32.add (global.get $gc-calls) (i32.const 1)))
		(global.set $reentry-stack (local.get $stack))
		(global.set $reentry-control (global.get $control-count))
		(global.set $pending-import (i32.const -1))
		(global.set $resuming (i32.const 0))
		(global.set $exception-pending (i32.const 0))
		(global.set $start-state (i32.const 0))
		(i32.const M4_ERR_SUCCESS)
	)

	;; Restore the outer import after nested result decoding, retaining all guest resource side effects.
	(func (export "end_reentry") (result i32)
		(local $frame i32)
		(local.set $frame (global.get $reentry-context))
		;; A completed nested invocation must still own a boundary to restore.
		(if (i32.eqz (local.get $frame))
			(then (return (i32.const M4_ERR_INVALID_RESUME)))
		)
		(global.set $error (i32.load offset=M4_REENTRY_ERROR_OFFSET (local.get $frame)))
		(global.set $offset (i32.load offset=M4_REENTRY_OFFSET_OFFSET (local.get $frame)))
		(global.set $tok (i32.load offset=M4_REENTRY_TOK_OFFSET (local.get $frame)))
		(global.set $last-results (i32.load offset=M4_REENTRY_LAST_RESULTS_OFFSET (local.get $frame)))
		(global.set $sp (i32.load offset=M4_REENTRY_SP_OFFSET (local.get $frame)))
		(global.set $control-count (i32.load offset=M4_REENTRY_CONTROL_COUNT_OFFSET (local.get $frame)))
		(global.set $saved-calls (i32.load offset=M4_REENTRY_SAVED_CALLS_OFFSET (local.get $frame)))
		(global.set $saved-frame (i32.load offset=M4_REENTRY_SAVED_FRAME_OFFSET (local.get $frame)))
		(global.set $saved-fuel (i64.load offset=M4_REENTRY_SAVED_FUEL_OFFSET (local.get $frame)))
		(global.set $resuming (i32.load offset=M4_REENTRY_RESUMING_OFFSET (local.get $frame)))
		(global.set $pending-import (i32.load offset=M4_REENTRY_PENDING_IMPORT_OFFSET (local.get $frame)))
		(global.set $pending-offset (i32.load offset=M4_REENTRY_PENDING_OFFSET_OFFSET (local.get $frame)))
		(global.set $gc-calls (i32.load offset=M4_REENTRY_GC_CALLS_OFFSET (local.get $frame)))
		(global.set $gc-pc (i32.load offset=M4_REENTRY_GC_PC_OFFSET (local.get $frame)))
		(global.set $gc-stack-end (i32.load offset=M4_REENTRY_GC_STACK_END_OFFSET (local.get $frame)))
		(global.set $exception-pending (i32.load offset=M4_REENTRY_EXCEPTION_PENDING_OFFSET (local.get $frame)))
		(global.set $exception-value (i64.load offset=M4_REENTRY_EXCEPTION_VALUE_OFFSET (local.get $frame)))
		(global.set $start-state (i32.load offset=M4_REENTRY_START_STATE_OFFSET (local.get $frame)))
		(global.set $reentry-floor (i32.load offset=M4_REENTRY_REENTRY_FLOOR_OFFSET (local.get $frame)))
		(global.set $reentry-stack (i32.load offset=M4_REENTRY_REENTRY_STACK_OFFSET (local.get $frame)))
		(global.set $reentry-control (i32.load offset=M4_REENTRY_REENTRY_CONTROL_OFFSET (local.get $frame)))
		(global.set $reentry-context (i32.load offset=M4_REENTRY_REENTRY_CONTEXT_OFFSET (local.get $frame)))
		(i32.const M4_ERR_SUCCESS)
	)
