m4_dnl Shared interpreter status codes, value types, dispatch families and record layout.
m4_dnl
m4_dnl Status codes shared with the Node host ABI.
m4_define(<!M4_ERR_SUCCESS!>,<!0!>)m4_dnl
m4_define(<!M4_ERR_SYNTAX!>,<!1!>)m4_dnl
m4_define(<!M4_ERR_UNSUPPORTED!>,<!2!>)m4_dnl
m4_define(<!M4_ERR_INTEGER_RANGE!>,<!3!>)m4_dnl
m4_define(<!M4_ERR_UNKNOWN_EXPORT!>,<!4!>)m4_dnl
m4_define(<!M4_ERR_INVALID_BUFFER!>,<!5!>)m4_dnl
m4_define(<!M4_ERR_RESOURCE_LIMIT!>,<!6!>)m4_dnl
m4_define(<!M4_ERR_OPERAND_STACK!>,<!7!>)m4_dnl
m4_define(<!M4_ERR_DIVIDE_BY_ZERO!>,<!8!>)m4_dnl
m4_define(<!M4_ERR_INTEGER_OVERFLOW!>,<!9!>)m4_dnl
m4_define(<!M4_ERR_INVALID_REFERENCE!>,<!10!>)m4_dnl
m4_define(<!M4_ERR_ARGUMENT_MISMATCH!>,<!11!>)m4_dnl
m4_define(<!M4_ERR_EXHAUSTED_FUEL!>,<!12!>)m4_dnl
m4_define(<!M4_ERR_UNREACHABLE!>,<!13!>)m4_dnl
m4_define(<!M4_ERR_MEMORY_BOUNDS!>,<!14!>)m4_dnl
m4_define(<!M4_ERR_MEMORY_LIMITS!>,<!15!>)m4_dnl
m4_define(<!M4_ERR_IMMUTABLE_GLOBAL!>,<!16!>)m4_dnl
m4_define(<!M4_ERR_INTERPRETER!>,<!17!>)m4_dnl
m4_define(<!M4_ERR_EXPORT_KIND!>,<!18!>)m4_dnl
m4_define(<!M4_ERR_ALIGNMENT!>,<!19!>)m4_dnl
m4_define(<!M4_ERR_HOST_IMPORT!>,<!20!>)m4_dnl
m4_define(<!M4_ERR_INVALID_RESUME!>,<!21!>)m4_dnl
m4_define(<!M4_ERR_SUSPENDED_REENTRY!>,<!22!>)m4_dnl
m4_define(<!M4_ERR_HOST_VALUE_TYPE!>,<!23!>)m4_dnl
m4_define(<!M4_ERR_UNDEFINED_ELEMENT!>,<!24!>)m4_dnl
m4_define(<!M4_ERR_INDIRECT_TYPE!>,<!25!>)m4_dnl
m4_define(<!M4_ERR_TABLE_LIMITS!>,<!26!>)m4_dnl
m4_define(<!M4_ERR_ELEMENT_BOUNDS!>,<!27!>)m4_dnl
m4_define(<!M4_ERR_INVALID_CONVERSION!>,<!28!>)m4_dnl
m4_define(<!M4_ERR_NOT_INITIALIZED!>,<!29!>)m4_dnl
m4_define(<!M4_ERR_TABLE_BOUNDS!>,<!30!>)m4_dnl
m4_define(<!M4_ERR_NULL_REFERENCE!>,<!31!>)m4_dnl
m4_define(<!M4_ERR_CAST_FAILURE!>,<!32!>)m4_dnl
m4_define(<!M4_ERR_ARRAY_BOUNDS!>,<!33!>)m4_dnl
m4_define(<!M4_ERR_UNCAUGHT_EXCEPTION!>,<!34!>)m4_dnl
m4_dnl
m4_dnl Generated runtime dispatch families; zero uses the general path.
m4_define(<!M4_ROUTE_GENERAL!>,<!0!>)m4_dnl
m4_define(<!M4_ROUTE_CONSTANT_LOCAL!>,<!1!>)m4_dnl
m4_define(<!M4_ROUTE_INTEGER!>,<!2!>)m4_dnl
m4_define(<!M4_ROUTE_CONTROL!>,<!3!>)m4_dnl
m4_define(<!M4_ROUTE_GLOBAL_REFERENCE!>,<!4!>)m4_dnl
m4_define(<!M4_ROUTE_CALL!>,<!5!>)m4_dnl
m4_define(<!M4_ROUTE_UNREACHABLE!>,<!6!>)m4_dnl
m4_define(<!M4_ROUTE_RETURN!>,<!7!>)m4_dnl
m4_define(<!M4_ROUTE_THROW!>,<!8!>)m4_dnl
m4_define(<!M4_ROUTE_CAST_BRANCH!>,<!9!>)m4_dnl
m4_define(<!M4_ROUTE_REFERENCE_BRANCH!>,<!10!>)m4_dnl
m4_define(<!M4_ROUTE_BRANCH!>,<!11!>)m4_dnl
m4_define(<!M4_ROUTE_SELECT!>,<!12!>)m4_dnl
m4_define(<!M4_ROUTE_GC_AGGREGATE!>,<!13!>)m4_dnl
m4_define(<!M4_ROUTE_TABLE!>,<!14!>)m4_dnl
m4_define(<!M4_ROUTE_MEMORY!>,<!15!>)m4_dnl
m4_dnl
m4_dnl Scalar/vector value type IDs.
m4_define(<!M4_TYPE_I32!>,<!1!>)m4_dnl
m4_define(<!M4_TYPE_I64!>,<!2!>)m4_dnl
m4_define(<!M4_TYPE_F32!>,<!3!>)m4_dnl
m4_define(<!M4_TYPE_F64!>,<!4!>)m4_dnl
m4_define(<!M4_TYPE_V128!>,<!5!>)m4_dnl
m4_dnl
m4_dnl Record widths, packed table locations and field offsets.
m4_define(<!M4_SLOT_BYTES!>,<!8!>)m4_dnl
m4_define(<!M4_SLOT_SHIFT!>,<!3!>)m4_dnl
m4_define(<!M4_INSTRUCTION_BYTES!>,<!16!>)m4_dnl
m4_define(<!M4_INSTRUCTION_SHIFT!>,<!4!>)m4_dnl
m4_define(<!M4_EFFECT_TABLE_BASE!>,<!3072!>)m4_dnl
m4_define(<!M4_ROUTE_TABLE_BASE!>,<!3480!>)m4_dnl
m4_define(<!M4_NIBBLE_MASK!>,<!15!>)m4_dnl
m4_define(<!M4_NIBBLE_SHIFT!>,<!4!>)m4_dnl
m4_define(<!M4_INSTRUCTION_IMMEDIATE_OFFSET!>,<!4!>)m4_dnl
m4_define(<!M4_INSTRUCTION_SOURCE_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_INSTRUCTION_EXTRA_OFFSET!>,<!12!>)m4_dnl
m4_define(<!M4_CALL_END_OFFSET!>,<!4!>)m4_dnl
m4_define(<!M4_CALL_STACK_BASE_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_CALL_FUNCTION_OFFSET!>,<!12!>)m4_dnl
m4_define(<!M4_CALL_LOCALS_OFFSET!>,<!16!>)m4_dnl
m4_define(<!M4_CONTROL_START_OFFSET!>,<!4!>)m4_dnl
m4_define(<!M4_CONTROL_END_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_CONTROL_STACK_BASE_OFFSET!>,<!12!>)m4_dnl
m4_define(<!M4_CONTROL_RESULT_SHAPE_OFFSET!>,<!16!>)m4_dnl
m4_define(<!M4_CONTROL_PARAMETER_SHAPE_OFFSET!>,<!20!>)m4_dnl
m4_define(<!M4_FUNCTION_START_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_FUNCTION_END_OFFSET!>,<!12!>)m4_dnl
m4_define(<!M4_FUNCTION_PARAMETERS_OFFSET!>,<!16!>)m4_dnl
m4_define(<!M4_FUNCTION_LOCALS_OFFSET!>,<!20!>)m4_dnl
m4_define(<!M4_FUNCTION_RESULT_SHAPE_OFFSET!>,<!24!>)m4_dnl
m4_dnl
m4_dnl Numeric boundaries and opcode-specific metadata fields.
m4_define(<!M4_U32_MAX!>,<!4294967295!>)m4_dnl
m4_define(<!M4_I32_MIN!>,<!-2147483648!>)m4_dnl
m4_define(<!M4_I64_MIN!>,<!-9223372036854775808!>)m4_dnl
m4_define(<!M4_WORD_BITS!>,<!32!>)m4_dnl
m4_define(<!M4_METADATA_ELSE_OFFSET!>,<!4!>)m4_dnl
m4_define(<!M4_METADATA_PARAMETER_SHAPE_OFFSET!>,<!20!>)m4_dnl
m4_define(<!M4_GLOBAL_VALUE_OFFSET!>,<!24!>)m4_dnl
m4_define(<!M4_GLOBAL_HIGH_OFFSET!>,<!72!>)m4_dnl
m4_define(<!M4_MEMORY_ADDRESS_TYPE_OFFSET!>,<!24!>)m4_dnl
m4_define(<!M4_TABLE_ADDRESS_TYPE_OFFSET!>,<!24!>)m4_dnl
m4_define(<!M4_ELEMENT_LIVE_LENGTH_OFFSET!>,<!44!>)m4_dnl
m4_define(<!M4_VECTOR_HIGH_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_MEMORY_OPERAND_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_BULK_SOURCE_MEMORY_OFFSET!>,<!16!>)m4_dnl
m4_define(<!M4_BULK_SOURCE_TABLE_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_BULK_SOURCE_OFFSET!>,<!16!>)m4_dnl
m4_define(<!M4_BULK_SOURCE_ADDRESS_TYPE_OFFSET!>,<!24!>)m4_dnl
m4_define(<!M4_BRANCH_TYPE_OFFSET!>,<!8!>)m4_dnl
m4_define(<!M4_U32_BYTES!>,<!4!>)m4_dnl
m4_define(<!M4_FUNCTION_IMPORTED!>,<!-1!>)m4_dnl
m4_define(<!M4_INDEX_ABSENT!>,<!-1!>)m4_dnl
m4_define(<!M4_TABLE_OPERAND_OFFSET!>,<!8!>)m4_dnl
m4_dnl Decimal digit and scale chunks fit in one unsigned multiplier limb.
m4_define(<!M4_DECIMAL_RADIX!>,<!10!>)m4_dnl
m4_define(<!M4_DECIMAL_CHUNK_DIGITS!>,<!9!>)m4_dnl
m4_define(<!M4_DECIMAL_CHUNK_RADIX!>,<!1000000000!>)m4_dnl
m4_dnl Fixed-width SIMD lane addressing and masks.
m4_define(<!M4_VECTOR_HALF_BITS!>,<!64!>)m4_dnl
m4_define(<!M4_LANE8_SHIFT!>,<!3!>)m4_dnl
m4_define(<!M4_LANE16_SHIFT!>,<!4!>)m4_dnl
m4_define(<!M4_LANE32_SHIFT!>,<!5!>)m4_dnl
m4_define(<!M4_LANE64_SHIFT!>,<!6!>)m4_dnl
m4_define(<!M4_U8_MAX!>,<!255!>)m4_dnl
m4_define(<!M4_U16_MAX!>,<!65535!>)m4_dnl
m4_dnl Exact integer scratch buffers contain a header and 32-bit limbs.
m4_define(<!M4_BIG_LIMB_BYTES!>,<!4!>)m4_dnl
m4_define(<!M4_BIG_LIMB_BITS!>,<!32!>)m4_dnl
m4_define(<!M4_BIG_LIMB_CAPACITY!>,<!1023!>)m4_dnl
m4_dnl Seven hexadecimal digits form a multiplier of 16^7 within one unsigned limb.
m4_define(<!M4_HEX_CHUNK_RADIX!>,<!268435456!>)m4_dnl
m4_dnl The four exact WAT whitespace bytes, shared by helper and inline scanner checks.
m4_define(<!M4_BYTE_SPACE!>,<!32!>)m4_dnl
m4_define(<!M4_BYTE_TAB!>,<!9!>)m4_dnl
m4_define(<!M4_BYTE_LF!>,<!10!>)m4_dnl
m4_define(<!M4_BYTE_CR!>,<!13!>)m4_dnl
m4_dnl Bytes that can introduce WAT comments or annotations.
m4_define(<!M4_BYTE_LPAREN!>,<!40!>)m4_dnl
m4_define(<!M4_BYTE_SEMICOLON!>,<!59!>)m4_dnl
m4_dnl ASCII digit decoding uses unsigned ranges and the ASCII lowercase case bit.
m4_define(<!M4_ASCII_ZERO!>,<!48!>)m4_dnl
m4_define(<!M4_DECIMAL_LAST_DIGIT!>,<!9!>)m4_dnl
m4_define(<!M4_ASCII_CASE_BIT!>,<!32!>)m4_dnl
m4_define(<!M4_ASCII_LOWER_A!>,<!97!>)m4_dnl
m4_define(<!M4_HEX_LAST_LETTER!>,<!5!>)m4_dnl
